services:
  - type: web
    name: student-management-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student_management  
          property: connectionString
